import torch
import numpy as np
import matplotlib.pyplot as plt
import os

import sys
sys.path.append("src")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

os.chdir('/home/george-vengrovski/Documents/projects/tweety_bert_paper')

from experiment_manager import ExperimentRunner

#Initialize experiment runner
experiment_runner = ExperimentRunner(device="cuda")

# Define configurations
configurations = [
        {"experiment_name": "llb3_train_25", "loss_function": "compute_loss", "plot_umap": False, "train_dir": "files/llb3_train_25", "test_dir": "files/llb3_test_25", "batch_size": 64, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 25, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 10, "p": 0.015, "alpha": 1, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 1000, "save_interval": 9999, "umap_data_dir": "umap_eval_dataset_llb16", "remove_silences": False, "subsample": 1, "context": 1000, "time_bins_umap_point": 100, "weight_decay": 0, "tau":1},
        {"experiment_name": "llb3_train_100", "loss_function": "compute_loss", "plot_umap": False, "train_dir": "files/llb3_train_100", "test_dir": "files/llb3_test_100", "batch_size": 64, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 100, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 10, "p": 0.015, "alpha": 1, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 1000, "save_interval": 9999, "umap_data_dir": "umap_eval_dataset_llb16", "remove_silences": False, "subsample": 1, "context": 1000, "time_bins_umap_point": 100, "weight_decay": 0, "tau":1},
        {"experiment_name": "llb3_train_500", "loss_function": "compute_loss", "plot_umap": False, "train_dir": "files/llb3_train_500", "test_dir": "files/llb3_test_500", "batch_size": 64, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 500, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 10, "p": 0.015, "alpha": 1, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 1000, "save_interval": 9999, "umap_data_dir": "umap_eval_dataset_llb16", "remove_silences": False, "subsample": 1, "context": 1000, "time_bins_umap_point": 100, "weight_decay": 0, "tau":1}
        {"experiment_name": "llb11_train_25", "loss_function": "compute_loss", "plot_umap": False, "train_dir": "files/llb11_train_25", "test_dir": "files/llb11_test_25", "batch_size": 64, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 25, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 10, "p": 0.015, "alpha": 1, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 1000, "save_interval": 9999, "umap_data_dir": "umap_eval_dataset_llb16", "remove_silences": False, "subsample": 1, "context": 1000, "time_bins_umap_point": 100, "weight_decay": 0, "tau":1},
        {"experiment_name": "llb11_train_100", "loss_function": "compute_loss", "plot_umap": False, "train_dir": "files/llb11_train_100", "test_dir": "files/llb11_test_100", "batch_size": 64, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 100, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 10, "p": 0.015, "alpha": 1, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 1000, "save_interval": 9999, "umap_data_dir": "umap_eval_dataset_llb16", "remove_silences": False, "subsample": 1, "context": 1000, "time_bins_umap_point": 100, "weight_decay": 0, "tau":1},
        {"experiment_name": "llb11_train_500", "loss_function": "compute_loss", "plot_umap": False, "train_dir": "files/llb11_train_500", "test_dir": "files/llb11_test_500", "batch_size": 64, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 500, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 10, "p": 0.015, "alpha": 1, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 1000, "save_interval": 9999, "umap_data_dir": "umap_eval_dataset_llb16", "remove_silences": False, "subsample": 1, "context": 1000, "time_bins_umap_point": 100, "weight_decay": 0, "tau":1}
        {"experiment_name": "llb16_train_25", "loss_function": "compute_loss", "plot_umap": False, "train_dir": "files/llb16_train_25", "test_dir": "files/llb16_test_25", "batch_size": 64, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 25, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 10, "p": 0.015, "alpha": 1, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 1000, "save_interval": 9999, "umap_data_dir": "umap_eval_dataset_llb16", "remove_silences": False, "subsample": 1, "context": 1000, "time_bins_umap_point": 100, "weight_decay": 0, "tau":1},
        {"experiment_name": "llb16_train_100", "loss_function": "compute_loss", "plot_umap": False, "train_dir": "files/llb16_train_100", "test_dir": "files/llb16_test_100", "batch_size": 64, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 100, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 10, "p": 0.015, "alpha": 1, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 1000, "save_interval": 9999, "umap_data_dir": "umap_eval_dataset_llb16", "remove_silences": False, "subsample": 1, "context": 1000, "time_bins_umap_point": 100, "weight_decay": 0, "tau":1},
        {"experiment_name": "llb16_train_500", "loss_function": "compute_loss", "plot_umap": False, "train_dir": "files/llb16_train_500", "test_dir": "files/llb16_test_500", "batch_size": 64, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 500, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 10, "p": 0.015, "alpha": 1, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 1000, "save_interval": 9999, "umap_data_dir": "umap_eval_dataset_llb16", "remove_silences": False, "subsample": 1, "context": 1000, "time_bins_umap_point": 100, "weight_decay": 0, "tau":1}
]
for i, config in enumerate(configurations):
    experiment_runner.run_experiment(config, i)
