import torch
import numpy as np
import matplotlib.pyplot as plt
import os

import sys
sys.path.append("src")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

from experiment_manager import ExperimentRunner

#Initialize experiment runner
experiment_runner = ExperimentRunner(device="cuda")


# Define configurations
configurations = [
        {"experiment_name": "TweetyBERT-Pretrain-Song-Detector", "loss_function": "mse_loss", "train_dir": "files/songdetector_train", "test_dir": "files/songdetector_test", "batch_size": 24, "d_transformer": 384, "nhead_transformer": 8, "embedding_dim": 196, "num_clusters": 50, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 10, "p": 0.02, "alpha": .5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB11_No_Mask_50_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb11_train_50", "test_dir": "files/llb11_test_50", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 50, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 0, "p": 0.001, "alpha": 0, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB16_No_Mask_50_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb16_train_50", "test_dir": "files/llb16_test_50", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 50, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 0, "p": 0.001, "alpha": 0, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB3_No_Mask_500_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb3_train_500", "test_dir": "files/llb3_test_500", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 500, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 0, "p": 0.001, "alpha": 0, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB11_No_Mask_500_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb11_train_500", "test_dir": "files/llb11_test_500", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 500, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 0, "p": 0.001, "alpha": 0, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB16_No_Mask_500_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb16_train_500", "test_dir": "files/llb16_test_500", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 500, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 0, "p": 0.001, "alpha": 0, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB3_10_Mask_50_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb3_train_50", "test_dir": "files/llb3_test_50", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 50, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 10, "p": 0.02, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB11_10_Mask_50_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb11_train_50", "test_dir": "files/llb11_test_50", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 50, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 10, "p": 0.02, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB16_10_Mask_50_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb16_train_50", "test_dir": "files/llb16_test_50", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 50, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 10, "p": 0.02, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB3_10_Mask_500_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb3_train_500", "test_dir": "files/llb3_test_500", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 500, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 10, "p": 0.02, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB11_10_Mask_500_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb11_train_500", "test_dir": "files/llb11_test_500", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 500, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 10, "p": 0.02, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB16_10_Mask_500_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb16_train_500", "test_dir": "files/llb16_test_500", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 500, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 10, "p": 0.02, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB3_50_Mask_50_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb3_train_50", "test_dir": "files/llb3_test_50", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 50, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 50, "p": 0.004, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB11_50_Mask_50_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb11_train_50", "test_dir": "files/llb11_test_50", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 50, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 50, "p": 0.004, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB16_50_Mask_50_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb16_train_50", "test_dir": "files/llb16_test_50", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 50, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 50, "p": 0.004, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB3_50_Mask_500_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb3_train_500", "test_dir": "files/llb3_test_500", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 500, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 50, "p": 0.004, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB11_50_Mask_500_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb11_train_500", "test_dir": "files/llb11_test_500", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 500, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 50, "p": 0.004, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB16_50_Mask_500_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb16_train_500", "test_dir": "files/llb16_test_500", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 500, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 50, "p": 0.004, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB3_200_Mask_50_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb3_train_50", "test_dir": "files/llb3_test_50", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 50, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 50, "p": 0.004, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB11_200_Mask_50_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb11_train_50", "test_dir": "files/llb11_test_50", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 50, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 50, "p": 0.004, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB16_200_Mask_50_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb16_train_50", "test_dir": "files/llb16_test_50", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 50, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 50, "p": 0.004, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB3_200_Mask_500_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb3_train_500", "test_dir": "files/llb3_test_500", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 500, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 50, "p": 0.004, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB11_200_Mask_500_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb11_train_500", "test_dir": "files/llb11_test_500", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 500, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 50, "p": 0.004, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
        # {"experiment_name": "TweetyBERT-cluster_LLB16_200_Mask_500_clusters", "loss_function": "cross_entropy", "train_dir": "files/llb16_train_500", "test_dir": "files/llb16_test_500", "batch_size": 48, "d_transformer": 196, "nhead_transformer": 4, "embedding_dim": 256, "num_clusters": 500, "dropout": 0.1, "dim_feedforward": 768, "transformer_layers": 4, "m": 50, "p": 0.004, "alpha": 0.5, "pos_enc_type": "relative", "learning_rate": 3e-4, "max_steps": 25e3, "eval_interval": 200, "save_interval": 1000, "remove_silences": False, "context": 1000, "weight_decay": 0, "tau":1,  "early_stopping": True, "patience": 4, "trailing_avg_window":200},
]

for i, config in enumerate(configurations):
    experiment_runner.run_experiment(config, i)
